apiVersion: v1
kind: Service
metadata:
  name: java-crud-service
  namespace: crud
spec:
  type: NodePort
  selector:
    app: java-crud
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30007
